use crate::git::GitEngine;
use pkm_core::PkmError;
use std::fs;

/// Describes a file that has sync conflicts.
#[derive(Debug, Clone)]
pub struct ConflictFile {
    pub path: String,
    pub our_diff: String,
    pub their_diff: String,
}

/// A single conflict hunk parsed from conflict markers.
#[derive(Debug, Clone)]
pub struct ConflictHunk {
    /// Lines from our side of the conflict.
    pub ours: String,
    /// Lines from their side of the conflict.
    pub theirs: String,
}

pub fn detect_conflicts(repo: &GitEngine) -> Result<Vec<ConflictFile>, PkmError> {
    let git_repo = repo.repository();

    // Open the index and check for entries with non-zero stage (1=base, 2=ours, 3=theirs)
    let index = match git_repo.open_index() {
        Ok(idx) => idx,
        Err(_) => return Ok(Vec::new()),
    };

    let state: &gix::index::State = &index;
    let has_conflicts = state.entries().iter().any(|e| e.stage() != gix::index::entry::Stage::Unconflicted);

    if !has_conflicts {
        return Ok(Vec::new());
    }

    // Collect unique conflict paths by looking at entries with stage != 0
    let mut conflict_paths: Vec<String> = state
        .entries()
        .iter()
        .filter(|e| e.stage() != gix::index::entry::Stage::Unconflicted)
        .filter_map(|e| {
            let path = e.path_in(state.path_backing());
            let path_str = path.to_string();
            if path_str.is_empty() { None } else { Some(path_str) }
        })
        .collect();
    conflict_paths.sort();
    conflict_paths.dedup();

    let mut conflicts = Vec::new();
    for path in conflict_paths {
        let our_diff = repo
            .diff(&path)
            .unwrap_or_else(|_| format!("(unable to compute diff for {path})"));

        let workdir_path = git_repo.workdir().map(|w| w.join(&path));
        let their_diff = match workdir_path {
            Some(p) => fs::read_to_string(p).unwrap_or_default(),
            None => String::new(),
        };

        conflicts.push(ConflictFile {
            path,
            our_diff,
            their_diff,
        });
    }

    Ok(conflicts)
}

/// Write conflict markers into a file so that a user can manually resolve.
///
/// This replaces the contents of the file at `path` with a three-way
/// conflict-marker format.
pub fn resolve_with_markers(
    path: &str,
    _base: &str,
    ours: &str,
    theirs: &str,
) -> Result<(), PkmError> {
    let content = format!("<<<<<<< ours\n{ours}\n=======\n{theirs}\n>>>>>>> theirs\n");
    fs::write(path, &content).map_err(PkmError::Io)?;
    Ok(())
}

/// Parse conflict markers from a string and return the hunks.
///
/// Recognises the standard `<<<<<<<`, `=======`, `>>>>>>>` markers.
pub fn parse_conflict_markers(content: &str) -> Vec<ConflictHunk> {
    let mut hunks = Vec::new();
    let mut in_conflict = false;
    let mut ours_lines = Vec::new();
    let mut theirs_lines = Vec::new();
    let mut in_ours = false;
    let mut in_theirs = false;

    for line in content.lines() {
        if line.starts_with("<<<<<<<") {
            in_conflict = true;
            in_ours = true;
            in_theirs = false;
            ours_lines.clear();
            theirs_lines.clear();
            continue;
        }
        if line.starts_with("=======") && in_conflict {
            in_ours = false;
            in_theirs = true;
            continue;
        }
        if line.starts_with(">>>>>>>") && in_conflict {
            in_conflict = false;
            in_ours = false;
            in_theirs = false;
            hunks.push(ConflictHunk {
                ours: ours_lines.join("\n"),
                theirs: theirs_lines.join("\n"),
            });
            ours_lines.clear();
            theirs_lines.clear();
            continue;
        }
        if in_ours {
            ours_lines.push(line);
        } else if in_theirs {
            theirs_lines.push(line);
        }
    }

    hunks
}

/// Create a structured sync conflict report file (Markdown).
///
/// Writes a `.sync-conflict.md` file that shows the original content alongside
/// both conflicting versions for easy manual resolution.
pub fn create_sync_conflict_file(
    path: &str,
    original: &str,
    ours: &str,
    theirs: &str,
) -> Result<(), PkmError> {
    let conflict_path = format!("{path}.sync-conflict.md");
    let content = format!(
        "# Sync Conflict: {path}\n\n\
         This file has a sync conflict that needs manual resolution.\n\n\
         ## Original\n\n```\n{original}\n```\n\n\
         ## Our Version (local)\n\n```\n{ours}\n```\n\n\
         ## Their Version (remote)\n\n```\n{theirs}\n```\n\n\
         ---\n*Generated by Stratum PKM Sync Engine*\n"
    );
    fs::write(&conflict_path, &content).map_err(PkmError::Io)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use tempfile::TempDir;

    #[test]
    fn test_parse_simple_conflict() {
        let content = r#"some text
<<<<<<< ours
my change
=======
their change
>>>>>>> theirs
more text"#;

        let hunks = parse_conflict_markers(content);
        assert_eq!(hunks.len(), 1);
        assert_eq!(hunks[0].ours, "my change");
        assert_eq!(hunks[0].theirs, "their change");
    }

    #[test]
    fn test_parse_multiple_conflicts() {
        let content = r#"<<<<<<< ours
first ours
=======
first theirs
>>>>>>> theirs
ok
<<<<<<< ours
second ours
=======
second theirs
>>>>>>> theirs"#;

        let hunks = parse_conflict_markers(content);
        assert_eq!(hunks.len(), 2);
        assert_eq!(hunks[0].ours, "first ours");
        assert_eq!(hunks[1].theirs, "second theirs");
    }

    #[test]
    fn test_parse_no_conflict() {
        let content = "just some normal text\nno markers here\n";
        let hunks = parse_conflict_markers(content);
        assert!(hunks.is_empty());
    }

    #[test]
    fn test_resolve_with_markers_writes_file() {
        let td = TempDir::new().unwrap();
        let path = td.path().join("conflict.md");
        let path_str = path.to_str().unwrap();

        resolve_with_markers(path_str, "base\n", "our line\n", "their line\n").unwrap();

        let content = fs::read_to_string(path).unwrap();
        assert!(content.contains("<<<<<<< ours"));
        assert!(content.contains("======="));
        assert!(content.contains(">>>>>>> theirs"));
        assert!(content.contains("our line"));
        assert!(content.contains("their line"));
    }

    #[test]
    fn test_create_sync_conflict_file_writes_markdown() {
        let td = TempDir::new().unwrap();
        let notes_dir = td.path().join("notes");
        fs::create_dir_all(&notes_dir).unwrap();
        let path = notes_dir.join("meeting.md");
        let path_str = path.to_str().unwrap();

        create_sync_conflict_file(path_str, "original notes", "my edits", "their edits").unwrap();

        let conflict_path = format!("{path_str}.sync-conflict.md");
        let content = fs::read_to_string(&conflict_path).unwrap();
        assert!(content.contains("# Sync Conflict:"));
        assert!(content.contains("my edits"));
        assert!(content.contains("their edits"));
        assert!(content.contains("original notes"));
    }

    #[test]
    fn test_detect_conflicts_no_conflicts() {
        let td = TempDir::new().unwrap();
        let engine = crate::git::GitEngine::init(td.path()).unwrap();

        // Write a file and commit
        fs::write(td.path().join("clean.md"), "clean").unwrap();
        engine.add(&["clean.md"]).unwrap();
        engine.commit("clean", "tester").unwrap();

        let conflicts = detect_conflicts(&engine).unwrap();
        assert!(conflicts.is_empty());
    }

    #[test]
    fn test_detect_conflicts_with_real_conflict() {
        // Note: Full branch-level merge conflict detection requires git2's merge API
        // which is not available in gix. This test verifies that conflict markers
        // in file content are handled correctly.
        let td = TempDir::new().unwrap();
        let engine = crate::git::GitEngine::init(td.path()).unwrap();

        // Create initial file on main
        fs::write(td.path().join("shared.md"), "line1\nline2\n").unwrap();
        engine.add(&["shared.md"]).unwrap();
        engine.commit("initial", "tester").unwrap();

        // detect_conflicts checks the index for stage != 0 entries.
        // Since we didn't create a merge conflict in the index (gix doesn't
        // expose git2's merge/index-conflict APIs), this is expected to
        // find no conflicts. The test verifies it doesn't crash.
        let conflicts = detect_conflicts(&engine).unwrap();
        // At minimum we should not crash or error
        assert!(conflicts.is_empty(), "expected no index conflicts (gix limitation)");
    }
}
